/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje3;


import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Ana_Ekrani_P extends javax.swing.JFrame {

    DefaultComboBoxModel dcm = new DefaultComboBoxModel();
    DefaultTableModel dtm = new DefaultTableModel();
    List<Urunler> urunler;

    /**
     * Creates new form AnaEkranP
     */
    public Ana_Ekrani_P() {
        initComponents();

        dtm.setColumnIdentifiers(new String[]{"Seri No", "Ürün Adı", "Kategori", "Marka", "Ürün Satış Fiyatı", "Adeti", "Ek Bilgi"});
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Proje3PU");
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();

        Query q = em.createQuery("select u from Urunler u");
        urunler = q.getResultList();
        for (Urunler urun : urunler) {
            dtm.addRow(new Object[]{urun.getUrunSeriNo(), urun.getUrunAdi(), urun.getUrunKategori(), urun.getUrunMarka(),
                urun.getUrunSatisFiyati(), urun.getUrunAdet(), urun.getUrunEkBilgi()});
        }
        table_Urunler.setModel(dtm);

        dcm.addElement("Telefon");
        dcm.addElement("Bilgisayar");
        dcm.addElement("Kamera");
        dcm.addElement("Oyun");
        ComboBox_Kategori.setModel(dcm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Field_Seri_No = new javax.swing.JTextField();
        txt_Field_Urun_Adi = new javax.swing.JTextField();
        txt_Field_Marka = new javax.swing.JTextField();
        txt_Field_Satis_Fiyati = new javax.swing.JTextField();
        ComboBox_Kategori = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_Field_Adet = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_Field_Alis_Fiyati = new javax.swing.JTextField();
        btn_Alis_Fiyati_Goster = new javax.swing.JButton();
        txt_Field_Ek_Bilgi = new javax.swing.JTextField();
        btn_Stok_Ekle = new javax.swing.JButton();
        btn_Seri_No_Ara = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Urunler = new javax.swing.JTable();
        btn__Stoklari_Duzenle = new javax.swing.JButton();
        btn_Stok_Sil = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        Menu_Borcular_Listesi = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STOK TAKİP PROGRAMI");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Seri No :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 18, -1, -1));

        jLabel2.setText("Ürün Adı :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 43, -1, -1));

        jLabel3.setText("Kategori :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 75, -1, -1));

        jLabel4.setText("Marka :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 104, -1, -1));

        jLabel5.setText("Satış Fiyatı :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 134, -1, -1));
        getContentPane().add(txt_Field_Seri_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 15, 184, -1));
        getContentPane().add(txt_Field_Urun_Adi, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 40, 184, -1));
        getContentPane().add(txt_Field_Marka, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 101, 184, -1));
        getContentPane().add(txt_Field_Satis_Fiyati, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 130, 190, -1));

        ComboBox_Kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        getContentPane().add(ComboBox_Kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 72, 184, -1));

        jLabel6.setText("Adet :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 13, -1, -1));
        getContentPane().add(txt_Field_Adet, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 13, 189, -1));

        jLabel7.setText("Ek Bilgi :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 41, -1, -1));

        jLabel8.setText("Alış Fiyatı :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 74, -1, -1));
        getContentPane().add(txt_Field_Alis_Fiyati, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 71, 86, -1));

        btn_Alis_Fiyati_Goster.setText("Goster");
        btn_Alis_Fiyati_Goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Alis_Fiyati_GosterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Alis_Fiyati_Goster, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 70, -1, -1));
        getContentPane().add(txt_Field_Ek_Bilgi, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 38, 189, -1));

        btn_Stok_Ekle.setText("Stok Ekle");
        btn_Stok_Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Stok_EkleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Stok_Ekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 131, 408, 34));

        btn_Seri_No_Ara.setText("ARA");
        btn_Seri_No_Ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Seri_No_AraActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Seri_No_Ara, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 14, 114, -1));

        table_Urunler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Seri_No", "Ürün_Adı", "Kategori", "Marka", "Satış_Fiyatı", "Adet", "Ek_Bilgi"
            }
        ));
        jScrollPane1.setViewportView(table_Urunler);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 249, 745, 257));

        btn__Stoklari_Duzenle.setText("Stokları Düzenle");
        btn__Stoklari_Duzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn__Stoklari_DuzenleActionPerformed(evt);
            }
        });
        getContentPane().add(btn__Stoklari_Duzenle, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 181, 320, 61));

        btn_Stok_Sil.setText("Stok Sil");
        btn_Stok_Sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Stok_SilActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Stok_Sil, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 372, 61));

        jMenu7.setText("Menü");
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        Menu_Borcular_Listesi.setText("Borçlular Listesi");
        Menu_Borcular_Listesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Borcular_ListesiActionPerformed(evt);
            }
        });
        jMenu7.add(Menu_Borcular_Listesi);

        jMenuBar2.add(jMenu7);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Stok_EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Stok_EkleActionPerformed
        try {
            PrintWriter pw = new PrintWriter(new FileWriter("Urunler.txt", false));
            pw.println(txt_Field_Adet.getText() + " Adet " + txt_Field_Urun_Adi.getText());
            pw.close();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, "Hata");
        }

        Urunler urun = new Urunler();
        try {
            urun.setUrunSeriNo(Integer.parseInt(txt_Field_Seri_No.getText()));
            urun.setUrunAdi(txt_Field_Urun_Adi.getText());
            urun.setUrunKategori(ComboBox_Kategori.getSelectedItem().toString());
            urun.setUrunMarka(txt_Field_Marka.getText());
            urun.setUrunAdet(Integer.parseInt(txt_Field_Adet.getText()));
            urun.setUrunAlisFiyati(Integer.parseInt(txt_Field_Alis_Fiyati.getText()));
            urun.setUrunSatisFiyati(Integer.parseInt(txt_Field_Satis_Fiyati.getText()));
            urun.setUrunEkBilgi(txt_Field_Ek_Bilgi.getText());

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Proje3PU");
            EntityManager em = emf.createEntityManager();
            em.getTransaction().begin();
            em.persist(urun);
            em.getTransaction().commit();

            dtm.addRow(new Object[]{urun.getUrunSeriNo(), urun.getUrunAdi(), urun.getUrunKategori(), urun.getUrunMarka(),
                urun.getUrunSatisFiyati(), urun.getUrunAdet(), urun.getUrunEkBilgi()});
            table_Urunler.setModel(dtm);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Hata");
        }

    }//GEN-LAST:event_btn_Stok_EkleActionPerformed

    private void btn__Stoklari_DuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn__Stoklari_DuzenleActionPerformed
        try {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Proje3PU");
            EntityManager em = emf.createEntityManager();
            Query q = em.createQuery("UPDATE Urunler u SET u.urunAdi=:urunadi,u.urunKategori=:urunkategori,u.urunMarka=:urunmarka,u.urunSatisFiyati=:urunsatisfiyati,u.urunEkBilgi=:urunekbilgi WHERE u.urunSeriNo=:urunserino");
            q.setParameter("urunadi", txt_Field_Urun_Adi.getText());
            q.setParameter("urunkategori", ComboBox_Kategori.getSelectedItem().toString());
            q.setParameter("urunmarka", txt_Field_Marka.getText());
            q.setParameter("urunsatisfiyati", Integer.parseInt(txt_Field_Satis_Fiyati.getText()));
            q.setParameter("urunekbilgi", txt_Field_Ek_Bilgi.getText());
            q.setParameter("urunserino", table_Urunler.getValueAt(table_Urunler.getSelectedRow(), 0));
            em.getTransaction().begin();
            q.executeUpdate();
            em.getTransaction().commit();

            dtm.setRowCount(0);
            Query q1 = em.createQuery("select u from Urunler u ");
            List<Urunler> urunler = q1.getResultList();
            for (Urunler urun : urunler) {
                dtm.addRow(new Object[]{urun.getUrunSeriNo(), urun.getUrunAdi(), urun.getUrunKategori(), urun.getUrunMarka(),
                    urun.getUrunSatisFiyati(), urun.getUrunAdet(), urun.getUrunEkBilgi()});
            }
            table_Urunler.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Hata");
        }

    }//GEN-LAST:event_btn__Stoklari_DuzenleActionPerformed

    private void btn_Seri_No_AraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Seri_No_AraActionPerformed
        try {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Proje3PU");
            EntityManager em = emf.createEntityManager();

            dtm.setRowCount(0);
            Query q = em.createQuery("select u from Urunler u where u.urunSeriNo=:userino");
            q.setParameter("userino", urunler.get(Integer.parseInt(txt_Field_Seri_No.getText())).getUrunSeriNo() - 1);
            List<Urunler> urunler = q.getResultList();
            for (Urunler urun : urunler) {
                dtm.addRow(new Object[]{urun.getUrunSeriNo(), urun.getUrunAdi(), urun.getUrunKategori(), urun.getUrunMarka(),
                    urun.getUrunSatisFiyati(), urun.getUrunAdet(), urun.getUrunEkBilgi()});
            }
            table_Urunler.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Bu Seri No'lu Bir Ürün Stokta Yoktur");
        }


    }//GEN-LAST:event_btn_Seri_No_AraActionPerformed

    private void btn_Stok_SilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Stok_SilActionPerformed
        try {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Proje3PU");
            EntityManager em = emf.createEntityManager();
            Query q = em.createQuery("DELETE FROM Urunler u WHERE u.urunSeriNo=:urunserino");

            q.setParameter("urunserino", table_Urunler.getValueAt(table_Urunler.getSelectedRow(), 0));
            em.getTransaction().begin();
            q.executeUpdate();
            em.getTransaction().commit();

            dtm.setRowCount(0);
            Query q1 = em.createQuery("select u from Urunler u");

            List<Urunler> urunler = q1.getResultList();
            for (Urunler urun : urunler) {
                dtm.addRow(new Object[]{urun.getUrunSeriNo(), urun.getUrunAdi(), urun.getUrunKategori(), urun.getUrunMarka(),
                    urun.getUrunSatisFiyati(), urun.getUrunAdet(), urun.getUrunEkBilgi()});
            }
            table_Urunler.setModel(dtm);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, "Bu Seri No'lu Bir Ürün Stokta Yoktur");
        }

    }//GEN-LAST:event_btn_Stok_SilActionPerformed

    private void btn_Alis_Fiyati_GosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Alis_Fiyati_GosterActionPerformed
        try {
            for (Urunler urun : urunler) {
                txt_Field_Alis_Fiyati.setText(String.valueOf(urunler.get(table_Urunler.getSelectedRow()).getUrunAlisFiyati()));
            }
        } catch (Exception e) {
       JOptionPane.showMessageDialog(rootPane, "Lütfen Tablodan Bir Ürün Seçiniz");
        }


    }//GEN-LAST:event_btn_Alis_Fiyati_GosterActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void Menu_Borcular_ListesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Borcular_ListesiActionPerformed
        new Borclular_Listesi_P().setVisible(true);
    }//GEN-LAST:event_Menu_Borcular_ListesiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ana_Ekrani_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ana_Ekrani_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ana_Ekrani_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ana_Ekrani_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ana_Ekrani_P().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_Kategori;
    private javax.swing.JMenuItem Menu_Borcular_Listesi;
    private javax.swing.JButton btn_Alis_Fiyati_Goster;
    private javax.swing.JButton btn_Seri_No_Ara;
    private javax.swing.JButton btn_Stok_Ekle;
    private javax.swing.JButton btn_Stok_Sil;
    private javax.swing.JButton btn__Stoklari_Duzenle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_Urunler;
    private javax.swing.JTextField txt_Field_Adet;
    private javax.swing.JTextField txt_Field_Alis_Fiyati;
    private javax.swing.JTextField txt_Field_Ek_Bilgi;
    private javax.swing.JTextField txt_Field_Marka;
    private javax.swing.JTextField txt_Field_Satis_Fiyati;
    private javax.swing.JTextField txt_Field_Seri_No;
    private javax.swing.JTextField txt_Field_Urun_Adi;
    // End of variables declaration//GEN-END:variables
}
