/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje3;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Borclular_Listesi_P extends javax.swing.JFrame {

    DefaultComboBoxModel dcm = new DefaultComboBoxModel();
    DefaultTableModel dtm = new DefaultTableModel();
    List<Musteriler> musteriler;

    /**
     * Creates new form Borclular_Listesi_P
     */
    public Borclular_Listesi_P() {
        initComponents();
        dtm.setColumnIdentifiers(new String[]{"Müşteri Adı", "Borç Miktarı", "Son Ödeme Tarihi"});
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Proje3PU");
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();

        Query q = em.createQuery("select m from Musteriler m");
        musteriler = q.getResultList();
        for (Musteriler musteri : musteriler) {
            dcm.addElement(musteri.musterilerPK.getAdi() + " " + musteri.musterilerPK.getSoyadi());
        }
        Combo_Box_Musteriler.setModel(dcm);

        Query q1 = em.createQuery("select b from Borc b");
        List<Borc> borclular = q1.getResultList();
        for (Borc borclu : borclular) {

            dtm.addRow(new Object[]{borclu.getAdi(), borclu.getBorcmiktar(), borclu.getOdemetarih()});
        }
        jTable1.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Field_Borc_Miktari = new javax.swing.JTextField();
        txt_Field_Son_Odeme_Tarihi = new javax.swing.JTextField();
        Combo_Box_Musteriler = new javax.swing.JComboBox<>();
        btn_Borclu_Ekle = new javax.swing.JButton();
        txt_field_Musteri_Ekle = new javax.swing.JTextField();
        btn_Musteri_Ekle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STOK TAKİP PROGRAMI");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Müşteri Adı", "Borç Miktarı", "Son Ödeme Tarihi"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Müşteri Adı:");

        jLabel3.setText("Borç Miktari:");

        jLabel4.setText("Son Ödeme Tarihi :");

        btn_Borclu_Ekle.setText("Borçlu Ekle");
        btn_Borclu_Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Borclu_EkleActionPerformed(evt);
            }
        });

        btn_Musteri_Ekle.setText("Müşteri Ekle");
        btn_Musteri_Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Musteri_EkleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Borclu_Ekle)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_Field_Son_Odeme_Tarihi))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3))
                                    .addGap(54, 54, 54)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_Field_Borc_Miktari, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Combo_Box_Musteriler, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Musteri_Ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_field_Musteri_Ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Combo_Box_Musteriler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_field_Musteri_Ekle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Field_Borc_Miktari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Musteri_Ekle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Field_Son_Odeme_Tarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Borclu_Ekle)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Borclu_EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Borclu_EkleActionPerformed
        try {
            Borc borclu = new Borc();

            borclu.setAdi(Combo_Box_Musteriler.getSelectedItem().toString());
            borclu.setBorcmiktar(txt_Field_Borc_Miktari.getText());
            borclu.setOdemetarih(txt_Field_Son_Odeme_Tarihi.getText());

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Proje3PU");
            EntityManager em = emf.createEntityManager();
            em.getTransaction().begin();
            em.persist(borclu);
            em.getTransaction().commit();

            dtm.addRow(new Object[]{borclu.getAdi(), borclu.getBorcmiktar(), borclu.getOdemetarih()});
            jTable1.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Daha Önce Kullanılmış İsim");
        }

    }//GEN-LAST:event_btn_Borclu_EkleActionPerformed

    private void btn_Musteri_EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Musteri_EkleActionPerformed
        try {
            Musteriler musteri = new Musteriler(txt_field_Musteri_Ekle.getText(), "");

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Proje3PU");
            EntityManager em = emf.createEntityManager();

            em.getTransaction().begin();
            em.persist(musteri);
            em.getTransaction().commit();

            dcm.removeAllElements();
            Query q = em.createQuery("select m from Musteriler m");
            musteriler = q.getResultList();
            for (Musteriler musteri2 : musteriler) {
                dcm.addElement(musteri2.musterilerPK.getAdi() + " " + musteri2.musterilerPK.getSoyadi());
            }
            Combo_Box_Musteriler.setModel(dcm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Daha Önce Kullanılmış İsim");
        }


    }//GEN-LAST:event_btn_Musteri_EkleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Borclular_Listesi_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Borclular_Listesi_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Borclular_Listesi_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Borclular_Listesi_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Borclular_Listesi_P().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combo_Box_Musteriler;
    private javax.swing.JButton btn_Borclu_Ekle;
    private javax.swing.JButton btn_Musteri_Ekle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_Field_Borc_Miktari;
    private javax.swing.JTextField txt_Field_Son_Odeme_Tarihi;
    private javax.swing.JTextField txt_field_Musteri_Ekle;
    // End of variables declaration//GEN-END:variables
}
